BookStore/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
namespace BookStore.Controllers
{
    public class NguoiDungController : Controller
    {
        QLBanSachEntities5 db = new QLBanSachEntities5();

        // GET: NguoiDung
        
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangKy(KhachHang kh)
        {
            
            if (ModelState.IsValid)
            {
                //KHTT khtt = new KHTT();
                //khtt.MaKHTT = kh.MaKH;
                //insert du lieu
                db.KhachHangs.Add(kh);
                //db.KHTTs.Add(khtt);
                db.SaveChanges();
                return RedirectToAction("DangKyThanhCong");
            }
            return View();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {
      
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection f)
        {
           
            string sTaiKhoan = f["txtTaiKhoan"].ToString();
            string sMatKhau = f["txtMatKhau"].ToString();
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.TaiKhoan == sTaiKhoan && n.MatKhau == sMatKhau);
            if(sTaiKhoan == "admin"&& sMatKhau == "admin")
            {
                Session["TaiKhoan"] = kh;
                Session["admin"] = kh;
                return RedirectToAction("Index", "QuanLySanPham");
            }
            
            if(kh != null )
            {
                
                if (Session["GioHang"] is null)
                {
                    ViewBag.ThongBao = "Chúc mừng bạn đã đăng nhập thành công !";
                    Session.Add("TaiKhoan", kh);
                    //Session["TaiKhoan"] = kh;
                    
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    Session.Add("TaiKhoan", kh);
                    //Session["TaiKhoan"] = kh;
                    return RedirectToAction("GioHang", "GioHang");
                }
            }
            ViewBag.ThongBao = "Tên tài khoản hoặc mật khẩu không đúng !";
            return View();
        }

        public ActionResult DangKyThanhCong()
        {
            return View();
        }
        public ActionResult DangNhapThanhCong()
        {
           
            return View();
        }
        public ActionResult DangNhap1()
        {

            if (Session["TaiKhoan"] != null)
            {
                KhachHang kh = (KhachHang)Session["TaiKhoan"];
                ViewBag.ThongBao = kh.HoTen;
                return PartialView();
            }

            ViewBag.ThongBao = "Đăng Nhập";
            return PartialView();
        }
        [HttpGet]
        public ActionResult ThongTinKhachHang(int maKH)
        {
            KhachHang kh1 = db.KhachHangs.SingleOrDefault(n => n.MaKH == maKH);
            return View(kh1);
        }
        public ActionResult Thoat()
        {
            if (Session["TaiKhoan"] != null)
            {
                Session.Remove("TaiKhoan");
                Session.Remove("admin");
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index","Home");
        }
        [HttpGet]
        public ActionResult SuaThongTin(int maKH)
        {
            KhachHang khachhang = db.KhachHangs.Single(n => n.MaKH == maKH);
            return View(khachhang);
        }
        [HttpPost]
                [ValidateInput(true)]
        public ActionResult SuaThongTin(KhachHang khachhang, FormCollection f)
        {

            if (ModelState.IsValid)
            {
                //Thực hiện cập nhật trong model
                db.Entry(khachhang).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            //db.KhachHangs.Single(n => n.MaKH == kh.MaKH).MatKhau = f["password"].ToString();
            //kh1.MatKhau = f["password"].ToString();
            //db.SaveChanges();

            return RedirectToAction("ThongTinKhachHang", new { @maKH = khachhang.MaKH } );
        }
        [HttpGet]
        public ActionResult LichSuMuaHang(int maKH)
        {
            List<DonHang> dh = db.DonHangs.Where(o => o.MaKH == maKH).ToList();
            
            List<ChiTietDonHang> ctdh = new List<ChiTietDonHang>();
            foreach(var item in dh)
            {
                List<ChiTietDonHang> ex = db.ChiTietDonHangs.Where(n => n.MaDonHang == item.MaDonHang).ToList();
                foreach(var item1 in ex)
                {
                    ctdh.Add(item1);
                }
            }
            
            //ChiTietDonHang ctdh = db.ChiTietDonHangs.Where(n => n.MaDonHang == dh.MaDonHang).ToList();
            return View(ctdh.ToList());
        }
    }
}

BookStore/Views/NguoiDung/DangKy.cshtml
@model BookStore.Models.KhachHang

@{
    ViewBag.Title = "Đăng ký";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}

<style>

    #chudeHienThi {
        display: none;
    }

    #nxbHienThi {
        display: none;
    }

    #anleftslider {
        display: none;
    }
</style>

<div id="dangky">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


    <div class="form">
        <h4>Đăng ký</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <table style="width:100%" id="table">
            <tr>
                <th>
                    <div class="form-group">
                        @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                            <span id="loiHoTen"></span>
                            @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </th>
                <th>
                    <div class="form-group">
                        @Html.LabelFor(model => model.TaiKhoan, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </th>

            </tr>
            <Hr style="background-color:black" />
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @*@Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })*@
                            @Html.PasswordFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
            </tr>

            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </td>
                <td>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                            <span id="loiNgaySinh"></span>
                            @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
            </tr>
        </table>

  

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="btnSubmit" type="submit" value="Đăng Ký" class="btn btn-default" />
                <a  class="theAb" title="Trở về" style=" " href="@Url.Action("Index","Home")">Trở về</a>
            </div>
        </div>
    </div>
    }
</div>
<div id="theA">
    
</div>
<style>
    .theAb {
        display: inline-block;
        width: 150px;
        height: 50px;
        color: black;
        background-color: orangered;
        border: 0.5px solid rgb(255, 255,255);
        text-align: center;
        line-height: 50px;
        font-size: 20px;
        font-weight: bold;
    }

    #theA a:hover {
        text-decoration: none;
        background-color: chocolate;
        -webkit-transition: all .5s ease-out;

    }

    #dangky div {
        font-size: 20px;
        font-weight: bold;
    }

    #btnSubmit {
        width: 150px;
        height: 50px;
        color: black;
        background-color: orangered;
        border: 0.5px solid rgb(255, 255,255);
        text-align: center;
        line-height: 50px;
        font-size: 20px;
        font-weight: bold;
        margin-top: 10px;
        margin-left:30%;

    }

    #dangky {
        padding: 20px;
        background-color: PaleGoldenrod;
    }

</style>

BookStore/Views/NguoiDung/DangKyThanhCong.cshtml
@{
    ViewBag.Title = "DangKyThanhCong";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}
<div style="background-color:white">
    <hr id="hr" />
         <div id="Dangkytc"
        <h2 style="margin-left:30px">Chúc mừng bạn đăng ký thành công, nhấn vào <a href="@Url.Action("DangNhap","NguoiDung")">đây</a> để vào trang đăng nhập.</h2>
        </div>
    <hr id="hr" />
</div>
<style>
    #Dangkytc{
        font-size:20px;
        font-weight:bold;
        margin:10px 30px 10px 0;
    }
    #Dangkytc a{
        text-decoration:underline;
    }
    #Dangkytc a:hover{
        width:20px;
        height:20px;
        background-color: orange;
        
    }
    #hr{
        padding:0;
        margin:0;
        border:none;
        color:black;
        background-color:black;
    
    }
</style>

BookStore/Views/NguoiDung/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}

<style>

    #chudeHienThi {
        display: none;
    }

    #nxbHienThi {
        display: none;
    }

    #anleftslider {
        display: none;
    }
</style>
<hr style="padding:0;margin:0;border:none;background-color:black;color:black;margin-bottom:20px;" />

<div id="dangnhap">
    <h2>Đăng nhập</h2>
    <h1>@ViewBag.ThongBao</h1>

    @using (Html.BeginForm())
    {
        <span>Tài khoản: </span>
        <br />
        @Html.TextBox("txtTaiKhoan");
        <br />
        <span>Mật khẩu: </span>
        <br />
        <input name="txtMatKhau" type="password" />
        <br />
        <input type="submit" style="float:left" id="btnSubmit" name="btnSubmit" value="Đăng nhập"/>
    }
        <div id="theA">
            <a class="theA" href="@Url.Action("DangKy","NguoiDung")">Đăng ký</a>
        </div>
       
</div>
<hr style="padding:0;margin:0;border:none;background-color:black;color:black;margin-top:20px;" />
<style>
    #theA {
        /*position: absolute;
        top: 416px;
        left: 180px;*/
        margin-top:21.5px;
    }
        #theA a:hover {
            text-decoration: none;

            background-color:chocolate;
            -webkit-transition: all .5s ease-out;
        }
    .theA {
        background-color: orangered;
        padding: 10.5px 40px;
        color: black;
        -webkit-transition: all .5s ease-out;
    }
    #dangnhap {
        font-size: 20px;
        font-weight: bold;
        padding: 20px;
        background-color: PaleGoldenrod;
    }

    #btnSubmit {
        width: 150px;
        height: 50px;
        color: black;
        background-color: orangered;
        border: 0.5px solid rgb(255, 255,255);
        text-align: center;
        line-height: 50px;
        font-size: 20px;
        font-weight: bold;
        margin-top: 10px;

    }
</style>

BookStore/Views/NguoiDung/DangNhap1.cshtml
@using BookStore.Models;
@{KhachHang khang = (KhachHang) Session["TaiKhoan"]; }
@if (Session["TaiKhoan"] is null)
{
<a href="@Url.Action("DangNhap", "NguoiDung")"><i class="fas fa-sign-in-alt"></i> @ViewBag.ThongBao  </a>

}
else
{
<a href="@Url.Action("ThongTinKhachHang", "NguoiDung",new { @maKH = khang.MaKH })">@ViewBag.ThongBao  </a>
    <style>
        #hienthiDanKy{
            display:none;

        }
    </style>
}

BookStore/Views/NguoiDung/DangNhapThanhCong.cshtml
@{
    ViewBag.Title = "DangNhapThanhCong";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}

<div style="background-color:white">
    <hr id="hr" />
    <div id="Dangkytc"
        <h2 style="margin-left:30px">Chúc mừng bạn đăng nhập thành công, nhấn vào <a href="@Url.Action("Index","Home")">đây</a> để vào trang mua hàng.</h2>
        </div>
    <hr id="hr" />
</div>
<style>
    #Dangkytc {
        font-size: 20px;
        font-weight: bold;
        margin: 10px 30px 10px 0;
    }

        #Dangkytc a {
            text-decoration: underline;
        }

            #Dangkytc a:hover {
                width: 20px;
                height: 20px;
                background-color: orange;
            }

    #hr {
        padding: 0;
        margin: 0;
        border: none;
        color: black;
        background-color: black;
    }
</style>

BookStore/Views/NguoiDung/LichSuMuaHang.cshtml
@using BookStore.Models;
@model List<ChiTietDonHang>
@{
    ViewBag.Title = "LichSuMuaHang";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}


<style>

    #chudeHienThi {
        display: none;
    }

    #nxbHienThi {
        display: none;
    }

    #anleftslider {
        display: none;
    }
</style>


<hr style="color:black;background-color:black" />
<h2 style="margin-left:8%;font-size:30px;font-weight:normal;">Lịch sử mua hàng </h2>

<table id="divGioHang">
    @{ double i = 0;}
    <tr class="bold">
        <td>Ngày đặt</td>
        <td>Tên Sách</td>
        <td>Số lượng</td>

        <td>Đơn giá</td>
        <td>Tổng tiền của sản phẩm</td>
    </tr>

    @foreach (var item in Model)
    {
        i = i + Convert.ToDouble(@item.DonGia) * Convert.ToDouble(item.SoLuong);

    <tr>
        @{DateTime value = Convert.ToDateTime(item.DonHang.NgayDat);}
        @if (value.Day == DateTime.Now.Day && value.Month == DateTime.Now.Month)
        {
            <td style="background-color:orange;font-size:20px">@item.DonHang.NgayDat</td>
        }
        else
        {
            <td>@item.DonHang.NgayDat</td>
        }

        <td>
            <div>@item.SAch.TenSach</div>
        </td>
        <td>
            <div>@item.SoLuong</div>
        </td>


        <td>@String.Format("{0:0,0}", @item.DonGia) VNĐ</td>

        <td>@String.Format("{0:0,0}", @item.DonGia * item.SoLuong) VNĐ</td>
    </tr>
    }
    <tr>
        <td colspan="6" style="text-align:right;color:brown ">
            <h2 style="float:left">Tổng tiền đã mua: </h2>
            <span style="font-size:20px">@String.Format("{0:0,0}", i) VNĐ</span>
        </td>
    </tr>



</table>

<hr style="background-color:black; padding:0 ; margin:0 ; border:none; margin-top:20px" />
<style>
    #divGioHang {
        border: 2px solid #666666;
        margin-left: 8%;
    }
        #divGioHang .bold td{
            font-weight:bold;
            font-size:20px;
        }
        #divGioHang td {
            padding: 10px;
            border: 2px solid #666666;
        }

    .capnhatxoa {
        display: block;
        width: 191px;
        height: 50px;
        background-color: #CC9900;
        text-align: center;
        font-size: 16px;
        line-height: 50px;
        color: black;
        font-weight: normal;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    #divGioHang a:hover {
        background-color: #FF9900;
        background: #FF9900;
    }
</style>

BookStore/Views/NguoiDung/SuaThongTin.cshtml
@model BookStore.Models.KhachHang

@{
    ViewBag.Title = "SuaThongTin";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}

<h2>SuaThongTin</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>KhachHang</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.MaKH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaKH, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaiKhoan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
 
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
   
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
     
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LuotXem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LuotXem, new { htmlAttributes = new { @class = "form-control" } })
           
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div id="asd">
    @Html.ActionLink("Trở về", "ThongTinKhachHang", new { @maKH = Model.MaKH })
</div>
<hr style="padding:0;margin:0;border:none;background-color:black;margin-top:20px" />
<div style="clear:both"></div>
<style>
    #asd {
        margin-top: 25px;
        font-size: 20px;
    }

    #nxbleft {
        display: none;
    }

    #chudeHienThi {
        display: none;
    }

    .form-horizontal {
        margin-left: 40%;
        font-size: 15px;
        font-weight: normal;
    }

    #css input[type=submit] {
        padding: 0.7em 0.7em 0.7em 0.7em;
        font-size: 1em;
        font-weight: bold;
        font-family: "Open Sans";
        text-transform: uppercase;
        color: black;
        background-size: 54px 204px;
        background-color: coral;
        border-radius: 2em;
        border: 0.15em solid #F9C23C;
        cursor: pointer;
        transition: all 0.3s ease 0s;
    }

    #css [type="submit"]:hover {
        color: black;
        background-color: whitesmoke;
        border-color: #AAAAAA;
        background-position: 0.75em bottom;
        -webkit-transition: all 0.3s ease;
        transition: all 0.3s ease;
    }

    #css [type="submit"]:focus {
        background-position: 2em -4em;
        -webkit-transition: all 0.3s ease;
        transition: all 0.3s ease;
    }

    #css {
        font-family: 'Open Sans';
        font-style: normal;
        font-weight: 700;
        src: local('Open Sans Bold'), local('OpenSans-Bold'), url(https://themes.googleusercontent.com/static/fonts/opensans/v8/k3k702ZOKiLJc3WVjuplzHhCUOGz7vYGh680lGh-uXM.woff) format('woff');
    }


    #chudeHienThi {
        display: none;
    }

    #nxbHienThi {
        display: none;
    }

    #anleftslider {
        display: none;
    }
</style>

BookStore/Views/NguoiDung/ThongTinKhachHang.cshtml
@model BookStore.Models.KhachHang

@{
    ViewBag.Title = "ThongTinKhachHang";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}


<style>
    #chudeHienThi {
        display: none;
    }

    #nxbHienThi {
        display: none;
    }

    #anleftslider {
        display: none;
    }
</style>
<hr style="color:black;background-color:black" />
<h2 style="margin-left:8%;font-size:30px;font-weight:normal;">Thông tin của bạn </h2>

<table id="divGioHang">
    <tr>
        <td>Họ Tên</td>
        <td>Tài Khoản</td>

        <td>Email</td>
        <td>Địa chỉ</td>
        <td>Điện thoại</td>
        <td>
            Giới tính
        </td>
        <td>Ngày Sinh</td>
    </tr>



    <tr>
        <td style="min-width:300px">@Model.HoTen</td>

        <td >@Model.TaiKhoan</td>



        <td>@Model.Email</td>

        <td> @Model.DiaChi</td>

        <td> @Model.DienThoai</td>
        <td>
            @Model.GioiTinh
        </td>
        <td>@Model.NgaySinh</td>

    </tr>

    
    <tr>
        <td colspan="6" style="text-align:right;color:brown ">

            @if (Session["admin"] == null)
            {
                <a class="capnhatxoa" style="text-decoration:none;float:right" title="Sửa Thông Tin" href="@Url.Action("SuaThongTin","NguoiDung",new { @maKH = Model.MaKH })">Đổi mật khẩu</a>
                <a class="capnhatxoa" style="text-decoration:none;margin-right:5px;float:right" title="Sửa Thông Tin" href="@Url.Action("LichSuMuaHang", "NguoiDung", new { @maKH = Model.MaKH })">Lịch sử mua hàng</a>
            }
            else
            {
                <a class="capnhatxoa" style="text-decoration:none;float:right" title="Sửa Thông Tin" href="@Url.Action("SuaThongTin","NguoiDung",new { @maKH = Model.MaKH })">Đổi mật khẩu</a>
            }
        </td>
    </tr>

</table>

<hr style="background-color:black; padding:0 ; margin:0 ; border:none; margin-top:20px" />
<style>
    #divGioHang {
        border: 2px solid #666666;
    margin-left:8%;
    }

        #divGioHang td {
            padding: 10px;
            border: 2px solid #666666;
        }

    .capnhatxoa {
        display: block;
        width: 191px;
        height: 50px;
        background-color: #CC9900;
        text-align: center;
        font-size: 16px;
        line-height: 50px;
        color: black;
        font-weight: normal;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    #divGioHang a:hover {
        background-color: #FF9900;
        background: #FF9900;
    }
    /*#nivosliderHienThi{
        display:none;
    }*/
</style>