BookStore/Controllers/QuanLySanPhamController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
using PagedList;
using PagedList.Mvc;
namespace BookStore.Controllers
{
    public class QuanLySanPhamController : Controller   
    {

        // GET: QuanLySanPham
        QLBanSachEntities5 db = new QLBanSachEntities5();
        public ActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page??1);
            return View(db.SAches.ToList().OrderByDescending(n=>n.MaSach).ToPagedList(pageNumber,pageSize));
        }

        [HttpGet]
        public ActionResult ThemMoi()
        {

            ViewBag.MaChuDe = new SelectList(  db.ChuDes.ToList().OrderBy(n=>n.TenChuDe),"MaChuDe","TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n=>n.TenNXB), "MaNXB", "TenNXB");

            return View();
        }
        [HttpPost]
        [ValidateInput( false)]
        public ActionResult ThemMoi(SAch sach,HttpPostedFileBase fileUpload)
        {
            
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");
            if (fileUpload == null)
            {
                ViewBag.ThongBao = "Chọn hình ảnh";
                return View();
            }
            //them vao csdl
            if(ModelState.IsValid )
            {
                //Luu ten file
                var fileName = Path.GetFileName(fileUpload.FileName);
                //luu duong dan
                var path = Path.Combine(Server.MapPath("~/imgSP"), fileName);
                //kiem tra hinh anh da ton tai chua
                if (System.IO.File.Exists(path))
                {
                    ViewBag.ThongBao = "Hình ảnh đã tồn tại!";
                }
                else
                {
                    fileUpload.SaveAs(path);
                }
                sach.AnhBia = fileUpload.FileName;
                db.SAches.Add(sach);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
        //chinhsua
        [HttpGet]
        public ActionResult ChinhSua(int MaSach)
        {
            
            // lay sach theo ma sach
            SAch sach = db.SAches.SingleOrDefault(n => n.MaSach == MaSach);
            if(sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe", sach.MaChuDe);
        
            return View(sach);
        }
        [HttpPost]
        [ValidateInput(false)]
  
        public ActionResult ChinhSua(SAch sach,FormCollection  f )
        {

            //them vao csdl
            if (ModelState.IsValid)
            {
                //Thực hiện cập nhật trong model
                db.Entry(sach).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe", sach.MaChuDe);
           

            return RedirectToAction("Index");
        }
        public ActionResult HienThi(int MaSach)
        {
            SAch sach = db.SAches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
        [HttpGet]
        public ActionResult Xoa( int MaSach)
        {
            SAch sach = db.SAches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
        [HttpPost,ActionName("Xoa")]
        public ActionResult XacNhanXoa(int MaSach)
        {
            SAch sach = db.SAches.SingleOrDefault(n => n.MaSach == MaSach);
            if(sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.SAches.Remove(sach);
            db.SaveChanges();
 
            return RedirectToAction("Index");

        }


        [HttpGet]
        public ActionResult ThemChuDe()
        {
            return View();
        }
        [HttpPost]

        public ActionResult ThemChuDe(ChuDe cd)
        {
            if (ModelState.IsValid)
            {
                db.ChuDes.Add(cd);
                db.SaveChanges();

            }

            return RedirectToAction("XemChuDe");
        }

        [HttpGet]
        public ActionResult ThemNXB()
        {
            return View();
        }
        [HttpPost]

        public ActionResult ThemNXB(NhaXuatBan nxb)
        {
            if (ModelState.IsValid)
            {
                db.NhaXuatBans.Add(nxb);
                db.SaveChanges();

            }

            return RedirectToAction("XemNXB");
        }

        public ActionResult XemChuDe()
        {

            return View(db.ChuDes.OrderByDescending(n=>n.MaChuDe).ToList());
        }
       
        [HttpGet]
        public ActionResult ChinhSuaCD(int MaCD)
        {
            // lay sach theo ma sach
            ChuDe cd = db.ChuDes.SingleOrDefault(n => n.MaChuDe == MaCD);
            if (cd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(cd);
        }
        [HttpPost]

        public ActionResult ChinhSuaCD(ChuDe cd)
        {
            //them vao csdl
            if (ModelState.IsValid)
            {
                //Thực hiện cập nhật trong model
                db.Entry(cd).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("XemChuDe");
        }
        public ActionResult XemNXB()
        {

            return View(db.NhaXuatBans.OrderByDescending(n=>n.MaNXB).ToList());
        }

        [HttpGet]
        public ActionResult ChinhSuaNXB(int MaNXB)
        {
            // lay sach theo ma sach
            NhaXuatBan nxb = db.NhaXuatBans.SingleOrDefault(n => n.MaNXB == MaNXB);
            if (nxb == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(nxb);
        }
        [HttpPost]

        public ActionResult ChinhSuaNXB(NhaXuatBan nxb)
        {
            //them vao csdl
            if (ModelState.IsValid)
            {
                //Thực hiện cập nhật trong model
                db.Entry(nxb).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("XemNXB");
        }
 
        public ActionResult XemThongTinKhachHang()
        {

            return View(db.KhachHangs.ToList());
        }
        [HttpGet]
        public ActionResult SuaThongTin(int maKH)
        {
            KhachHang kh = db.KhachHangs.Single(n => n.MaKH == maKH);
            return View(kh);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SuaThongTin(KhachHang kh)
        {
            if (ModelState.IsValid)
            {
                //Thực hiện cập nhật trong model
                db.Entry(kh).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("XemThongTinKhachHang");
        }
        public ActionResult HienThiThongTin(int maKH)
        {
            KhachHang kh = db.KhachHangs.Single(n => n.MaKH == maKH);

            return View(kh);
        }


        public ActionResult XemDonHang()
        {
            return View(db.DonHangs.ToList());
        }
        public ActionResult HienThiDonHang(int maDH)
        {
            List<ChiTietDonHang> lstCTDH = db.ChiTietDonHangs.Where(n => n.MaDonHang == maDH).ToList();
            return View(lstCTDH.ToList());
        }
        //[HttpGet]
        //public ActionResult ChinhSua(int maDH)
        //{

        //}
    }


}

BookStore/Views/QuanLySanPham/ChinhSua.cshtml
@model BookStore.Models.SAch

@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h1>Chỉnh Sửa Thông Tin</h1>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr style="background-color:black" />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" style="display:none;">
        @Html.LabelFor(model => model.MaSach, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <span style="padding:5px 5px 0px 0px;font-size:18px">    : @Model.MaSach</span>
            @Html.Hidden("MaSach", Model.MaSach)
        </div>
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.TenSach, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.AnhBia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AnhBia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AnhBia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayCapNhat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NgayCapNhat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaNXB, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaNXB")
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaChuDe")
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Moi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Moi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Moi, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <textarea name="MoTa">@Model.MoTa</textarea>

        </div>
    </div>
    <hr style="background-color:black" />
    <br />
    <div class="form-group">
        <div id="css" class="col-md-offset-2 col-md-10">
            <form>
                <input value="Lưu chỉnh sửa" type="submit" />
            </form>
        </div>

    </div>
</div>
}

    <div style="font-size:20px;">
        @Html.ActionLink("Trở về", "Index")
    </div>
    <style>
        #css input[type=submit] {
            padding: 1em 1em 1em 1em;
            font-size: 2em;
            font-weight: bold;
            font-family: "Open Sans";
            text-transform: uppercase;
            color: black;
            background-size: 54px 204px;
            background-color:coral;
            border-radius: 2em;
            border: 0.15em solid #F9C23C;
            cursor: pointer;
            transition: all 0.3s ease 0s;
        }
        #css [type="submit"]:hover {
            color: #fff;
            background-color: #EAA502;
            border-color: #EAA502;
            background-position: 0.75em bottom;
            -webkit-transition: all 0.3s ease;
            transition: all 0.3s ease;
        }
        #css [type="submit"]:focus {
            background-position: 2em -4em;
            -webkit-transition: all 0.3s ease;
            transition: all 0.3s ease;
        }
        #css {
            font-family: 'Open Sans';
            font-style: normal;
            font-weight: 700;
            src: local('Open Sans Bold'), local('OpenSans-Bold'), url(https://themes.googleusercontent.com/static/fonts/opensans/v8/k3k702ZOKiLJc3WVjuplzHhCUOGz7vYGh680lGh-uXM.woff) format('woff');
        }
    </style>

BookStore/Views/QuanLySanPham/ChinhSuaCD.cshtml
@model BookStore.Models.ChuDe

@{
    ViewBag.Title = "ChinhSuaCD";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<hr />
<h2 style="margin-left:27%">Chỉnh sửa chủ đề</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" style="display:none">
        @Html.LabelFor(model => model.MaChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaChuDe, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TenChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenChuDe, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenChuDe, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        <div id="css" class="col-md-offset-2 col-md-10">
            <form>
                <input value="Lưu chỉnh sửa" type="submit" />
            </form>
            @Html.ActionLink("Trở về", "XemChuDe")
        </div>

    </div>
</div>
}

<div style="font-size:20px">
   
</div>
<style>
    #css input[type=submit] {
        padding: 0.7em 0.7em 0.7em 0.7em;
        font-size: 1em;
        font-weight: bold;
        font-family: "Open Sans";
        text-transform: uppercase;
        color: black;
        background-size: 54px 204px;
        background-color: coral;
        border-radius: 2em;
        border: 0.15em solid #F9C23C;
        cursor: pointer;
        transition: all 0.3s ease 0s;
    }

    #css [type="submit"]:hover {
        color: black;
        background-color: whitesmoke;
        border-color: #AAAAAA;
        background-position: 0.75em bottom;
        -webkit-transition: all 0.3s ease;
        transition: all 0.3s ease;
    }

    #css [type="submit"]:focus {
        background-position: 2em -4em;
        -webkit-transition: all 0.3s ease;
        transition: all 0.3s ease;
    }

    #css {
        font-family: 'Open Sans';
        font-style: normal;
        font-weight: 700;
        src: local('Open Sans Bold'), local('OpenSans-Bold'), url(https://themes.googleusercontent.com/static/fonts/opensans/v8/k3k702ZOKiLJc3WVjuplzHhCUOGz7vYGh680lGh-uXM.woff) format('woff');
    }
        #css a {
            font-size: 25px;
            color: coral;
            text-decoration: underline;
        }
</style>

BookStore/Views/QuanLySanPham/HienThiDonHang.cshtml
@model IEnumerable<BookStore.Models.ChiTietDonHang>

@{
    ViewBag.Title = "HienThiDonHang";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Đơn hàng</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MaDonHang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SAch.AnhBia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoLuong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DonGia)
        </th>
        <th>Thành tiền</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaDonHang)
        </td>
        <td>
            <img style="width:80px;height:80px;" src="@Url.Content("~/imgSP/"+item.SAch.AnhBia)" alt="Alternate Text" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoLuong)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DonGia)
        </td>
        @{ var tt = @item.SoLuong * @item.DonGia;}
        <td>
            @tt
        </td>
    </tr>
            }

</table>

BookStore/Views/QuanLySanPham/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.PagedList<BookStore.Models.SAch>
@{
    ViewBag.Title = "Quản lý sản phẩm";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<hr />

<div style="margin-left:30%;">


    <h1>Quản lý sản phẩm</h1>
</div>

@using (Html.BeginForm("KetQuaTimKiemQL", "TimKiem", FormMethod.Post))
{
    @Html.TextBox("txtTimKiem", "", htmlAttributes:
new {@class="textboxTimKiem",@placeholder="Nhập tên sách cần tìm....." })
    <button type="submit" style="padding: 0px 0px 0px 0px">
        <img src="~/img/search1.png" width="30px" height="30px" />
    </button>

}

<table class="table" style="clear:both">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().MaSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TenSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().GiaBan)
        </th>
        <th style="display:none">
            @Html.DisplayNameFor(model => model.First().MoTa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().AnhBia)
        </th>
        <th style="display:none">
            @Html.DisplayNameFor(model => model.First().NgayCapNhat)
        </th>
        <th >
            @Html.DisplayNameFor(model => model.First().SoLuongTon)
        </th>
        <th style="display:none">
            @Html.DisplayNameFor(model => model.First().MaNXB)
        </th>
        <th style="display:none">
            @Html.DisplayNameFor(model => model.First().MaChuDe)
        </th>
        <th style="display:none">
            @Html.DisplayNameFor(model => model.First().Moi)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr style="width:100%">
            <td style="width:2%">
                @Html.DisplayFor(modelItem => item.MaSach)
            </td>
            <td style="width:10%">
                @Html.DisplayFor(modelItem => item.TenSach)
            </td>
            <td style="width:5%">
                @Html.Label(string.Format("{0:0,0 } VNĐ", item.GiaBan))
            <td style="width:30%;display:none;">
                @Html.Raw(item.MoTa)
            </td>
            <td style="width:15%">
                <img src="@Url.Content("~/imgSP/"+item.AnhBia)" width="150" height="150" alt="@item.TenSach" />
            </td>
            <td style="width:8%;display:none;">
                @Html.DisplayFor(modelItem => item.NgayCapNhat)
            </td>
            <td width="15%">
                @Html.DisplayFor(modelItem => item.SoLuongTon)
            </td>
            <td style="width:5%;display:none;">
                @Html.DisplayFor(modelItem => item.NhaXuatBan.TenNXB)
            </td>
            <td style="width:6%;display:none">
                @Html.DisplayFor(modelItem => item.ChuDe.TenChuDe)
            </td>
            <td style="width:2%;display:none;">
                @Html.DisplayFor(modelItem => item.Moi)
            </td>
            <td >
                @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { @MaSach = item.MaSach }) <br />
                @Html.ActionLink("Hiển Thị", "HienThi", new { @MaSach = item.MaSach }) <br />
                @Html.ActionLink("Xóa", "Xoa", new { @MaSach = item.MaSach })
            </td>
        </tr>
    }

</table>
<div id="PhanTrang">
    <div class="abc">
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

    </div>

    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", "QuanLySanPham", new { @page = page }))
    </div>

</div>

<style>
    .MenuTrang li {
        padding: 0;
        margin: 0;
        border: none;
        display: inline;
        width: 40px;
        height: 40px;
        padding: 5px;
        margin: 5px;
        line-height: 45px;
        font-family: 'Times New Roman', Times, serif;
        font-weight: bold;
    }

    #PhanTrang {
        border-bottom: 1px solid #C9E4D6;
    }

    .abc {
        margin-left: 35px;
        margin-top: 5px;
        font-size: 25px;
        font-weight: bold;
        font-family: 'Times New Roman', Times, serif;
    }
    .table a{
        color: black;
        text-decoration:underline;
        
    }
    .table a:hover{
        background-color:coral;
    }
    /*searchCSS*/


</style>

BookStore/Views/QuanLySanPham/ThemMoi.cshtml
@model BookStore.Models.SAch

@{
    ViewBag.Title = "ThemMoi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}
<hr />
<div style="margin-left:30%;">

    <h1>Thêm mới sách</h1>
    </div>
    <hr style="background-color:black" />
    @*them thuoc tinh cho form ( upload img)*@
    @using (Html.BeginForm("ThemMoi", "QuanLySanPham", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.AnhBia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <input type="file" name="fileUpLoad" />
                @*thong bao trung`*@
                @ViewBag.ThongBao
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.NgayCapNhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayCapNhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNXB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNXB")

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaChuDe")

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Moi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Moi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Moi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="MoTa">Điền mô tả vào đây</textarea>
            </div>
        </div>
        <hr style="background-color:black" />
        <div class="form-group">
            <div id="css" class="col-md-offset-2 col-md-10">
                <form>
                    <input value="Tạo mới sách" type="submit" />
                </form>
                @Html.ActionLink("Trở Về", "Index")
            </div>

        </div>
        
    </div>
    }

    
    <style>
        #css input[type=submit] {
            padding: 0.7em 0.7em 0.7em 0.7em;
            font-size: 1em;
            font-weight: bold;
            font-family: "Open Sans";
            text-transform: uppercase;
            color: black;
            background-size: 54px 204px;
            background-color: coral;
            border-radius: 2em;
            border: 0.15em solid #F9C23C;
            cursor: pointer;
            transition: all 0.3s ease 0s;
        }

        #css [type="submit"]:hover {
            color: black;
            background-color: whitesmoke;
            border-color: #AAAAAA;
            background-position: 0.75em bottom;
            -webkit-transition: all 0.3s ease;
            transition: all 0.3s ease;
        }

        #css [type="submit"]:focus {
            background-position: 2em -4em;
            -webkit-transition: all 0.3s ease;
            transition: all 0.3s ease;
        }

        #css {
            font-family: 'Open Sans';
            font-style: normal;
            font-weight: 700;
            src: local('Open Sans Bold'), local('OpenSans-Bold'), url(https://themes.googleusercontent.com/static/fonts/opensans/v8/k3k702ZOKiLJc3WVjuplzHhCUOGz7vYGh680lGh-uXM.woff) format('woff');
          
        }
            #css a {
                font-size: 25px;
                color: coral;
                text-decoration:underline;
            }
    </style>