BookStore/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
using PagedList;
using PagedList.Mvc;
namespace BookStore.Controllers
{
    public class SachController : Controller
    {
        QLBanSachEntities5 db = new QLBanSachEntities5();
        // GET: Sach


        public PartialViewResult SachMoiPartial()
        {
            var listSachMoi = db.SAches.Take(3).ToList();
            return PartialView(listSachMoi);
        }
        public ViewResult xemChiTiet(int maSach =0)
        {
            SAch sach = db.SAches.SingleOrDefault(n=>n.MaSach == maSach);
            if (sach == null)
            {
                //Tra ve trang bao loi
                Response.StatusCode = 404;
                return null;
            }
            if(Session["TaiKhoan"] != null)
            {
                KhachHang kh = (KhachHang) Session["TaiKhoan"];
                KhachHang kh1 = db.KhachHangs.Single(n => n.MaKH == kh.MaKH);
                if (kh1.LuotXem == null)
                    kh1.LuotXem = 1;
                else
                    kh1.LuotXem += 1;
                db.SaveChanges();
            }
            if(sach.LuotXem == null)
                sach.LuotXem = 1;
            else
                sach.LuotXem += 1;

            db.SaveChanges();

            ViewBag.TenChuDe = db.ChuDes.Single(n => n.MaChuDe == sach.MaChuDe).TenChuDe;
            ViewBag.NhaXuatBan = db.NhaXuatBans.Single(n => n.MaNXB == sach.MaNXB).TenNXB;
            return View(sach);
        }

        public ViewResult hienThiSachMoi(int? page)
        {   
            int pageSize = 6;
            //tao bien so trang
            int pageNumber = (page ?? 1);
            return View(db.SAches.Where(n => n.Moi == 1).ToList().OrderBy(n => n.GiaBan).ToPagedList(pageNumber, pageSize));
        }
    }
}

BookStore/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
using PagedList;
using PagedList.Mvc;
namespace BookStore.Controllers
{
    public class TimKiemController : Controller
    {
        // GET: TimKiem
        QLBanSachEntities5 db = new QLBanSachEntities5();
        [HttpPost]
        public ActionResult KetQuaTimKiem(FormCollection f,int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 6;
            decimal idOrPrice = 0;
            bool check = decimal.TryParse(f["txtTimKiem"], out idOrPrice);
            if(check && idOrPrice > 0)
            {
                List<SAch> lstKQTK1 = db.SAches.Where(o => o.MaSach == idOrPrice).ToList();
                if(lstKQTK1.Count == 1)
                {
                    ViewBag.ThongBao = "Tìm theo mã sách = " + idOrPrice;
                    return View(lstKQTK1.ToPagedList(pageNumber, pageSize));
                }
                    pageSize = 12;
                    lstKQTK1 = db.SAches.Where(o => o.GiaBan == idOrPrice).ToList();
                    ViewBag.ThongBao = "Tìm theo giá bán = " + string.Format("{0:0,0 } VNĐ", idOrPrice ) ;
                    return View(lstKQTK1.ToPagedList(pageNumber,pageSize));
            }
            
            
            string sTuKhoa = f["txtTimKiem"].ToString();
            ViewBag.TuKhoa = sTuKhoa;
            List<SAch> lstKQTK = db.SAches.Where(n => n.TenSach.Contains(sTuKhoa)).ToList();
    
            if (lstKQTK.Count == 0 )
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm nào!";
                return View(db.SAches.OrderBy(n => n.GiaBan).ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count + " kết quả!";
            return View(lstKQTK.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));

        }
        [HttpGet]
        public ActionResult KetQuaTimKiem(string sTuKhoa, int? page)
        {
            ViewBag.TuKhoa = sTuKhoa;
            List<SAch> lstKQTK = db.SAches.Where(n => n.TenSach.Contains(sTuKhoa)).ToList();
            int pageNumber = (page ?? 1);
            int pageSize = 6;
            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm nào!";
                return View(db.SAches.OrderBy(n => n.GiaBan).ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count + " kết quả!";
            return View(lstKQTK.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));

        }






        [HttpGet]
        public ActionResult KetQuaTimKiemCD(string sTuKhoa, int? page)
        {
            ViewBag.TuKhoa = sTuKhoa;
            List<ChuDe> lstCD = db.ChuDes.Where(n => n.TenChuDe.Contains(sTuKhoa)).ToList();
            int pageSize = 8;
            int pageNumber = page ?? 1;
            if(lstCD.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy kết quả tương ứng!";
                return View(db.ChuDes.OrderBy(n=>n.TenChuDe).ToPagedList(pageNumber,pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy" + lstCD.Count() + " kết quả.";
            return View(lstCD.OrderBy(n => n.TenChuDe).ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        public ActionResult KetQuaTimKiemCD(FormCollection f, int? page)
        {
            string sTuKhoa = f["txtTimKiem"].ToString();
            ViewBag.TuKhoa = sTuKhoa;
            List<ChuDe> lstCD = db.ChuDes.Where(n => n.TenChuDe.Contains(sTuKhoa)).ToList();
            int pageSize = 8;
            int pageNumber = page ?? 1;
            if (lstCD.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy kết quả nào tương ứng !";
                return View(db.ChuDes.OrderBy(n => n.TenChuDe).ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstCD.Count() + " kết quả.";
            return View(lstCD.OrderBy(n => n.TenChuDe).ToPagedList(pageNumber, pageSize));
        }


        [HttpGet]
        public ActionResult KetQuaTimKiemQL(string sTuKhoa, int? page)
        {
            ViewBag.TuKhoa = sTuKhoa;
            List<SAch> lstKQTK = db.SAches.Where(n => n.TenSach.Contains(sTuKhoa)).ToList();
            int pageSize = 10;
            int pageNumber = page ?? 1;
            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm nào tương ứng !";
                return View(db.SAches.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count() + " kết quả.";
            return View(lstKQTK.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        public ActionResult KetQuaTimKiemQL(FormCollection f, int? page)
        {
            string sTuKhoa = f["txtTimKiem"].ToString();
            ViewBag.TuKhoa = sTuKhoa;
            List<SAch> lstKQTK = db.SAches.Where(n => n.TenSach.Contains(sTuKhoa)).ToList();
            int pageSize = 10;
            int pageNumber = page ?? 1;
            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm nào tương ứng !";
                return View(db.SAches.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count() + " kết quả.";
            return View(lstKQTK.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
        }

        
          [HttpGet]
        public ActionResult KetQuaTimKiemNXB(string sTuKhoa, int? page)
        {
            ViewBag.TuKhoa = sTuKhoa;
            List<NhaXuatBan> lstNXB = db.NhaXuatBans.Where(n => n.TenNXB.Contains(sTuKhoa)).ToList();
            int pageSize = 8;
            int pageNumber = page ?? 1;
            if (lstNXB.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm nào tương ứng !";
                return View(db.NhaXuatBans.OrderBy(n => n.TenNXB).ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstNXB.Count() + " kết quả.";
            return View(lstNXB.OrderBy(n => n.TenNXB).ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        public ActionResult KetQuaTimKiemNXB(FormCollection f, int? page)
        {
            string sTuKhoa = f["txtTimKiem"].ToString();
            ViewBag.TuKhoa = sTuKhoa;
       
            List<NhaXuatBan> lstNXB = db.NhaXuatBans.Where(n => n.TenNXB.Contains(sTuKhoa)).ToList();
            int pageSize = 8;
            int pageNumber = page ?? 1;
            if (lstNXB.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm nào tương ứng !";
                return View(db.NhaXuatBans.OrderBy(n => n.TenNXB).ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstNXB.Count() + " kết quả.";
            return View(lstNXB.OrderBy(n => n.TenNXB).ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult KetQuaTimKiemKH(string sTuKhoa, int? page)
        {
            ViewBag.TuKhoa = sTuKhoa;
            List<KhachHang> lstKH = db.KhachHangs.Where(n => n.HoTen.Contains(sTuKhoa)).ToList();
            
            if (lstKH.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy khách hàng nào tương ứng !";
                return View(db.KhachHangs.OrderBy(n => n.HoTen));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKH.Count() + " kết quả.";
            return View(lstKH.OrderBy(n => n.HoTen));
        }
        [HttpPost]
        public ActionResult KetQuaTimKiemKH(FormCollection f, int? page)
        {
            string sTuKhoa = f["txtTimKiem"].ToString();
            ViewBag.TuKhoa = sTuKhoa;

            List<KhachHang> lstKH = db.KhachHangs.Where(n => n.HoTen.Contains(sTuKhoa)).ToList();

            if (lstKH.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm nào tương ứng !";
                return View(db.KhachHangs.OrderBy(n => n.HoTen));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKH.Count() + " kết quả.";
            return View(lstKH.OrderBy(n => n.HoTen));
        }


    }
}

BookStore/Views/TimKiem/KetQuaTimKiem.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<BookStore.Models.SAch>
@{
    ViewBag.Title = "Kết quả tìm kiếm";
    Layout = "~/Views/Layout/NguoiDungLayout.cshtml";
}
<link href="~/Content/TrangChuCss/TrangChu1.css" rel="stylesheet" />

<hr style="padding:0;margin:0;border:none;background-color:black;" />
<div id="sachMoiXuatBan" style="clear:both;padding:13px 0px 0px 0px;font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;font-weight:bold;margin-left:90px;background-color:white;background:white">
    <h2>Kết quả tìm kiếm: </h2>
    @ViewBag.ThongBao   
</div>
<hr />


<div id="divBody" style="background:white">

    @{ int i = 0; }
    @{
        foreach (var item in Model)
        {
            i++;
            <div id="sanPham">
                <div id="anhBia">
                    <a href="@Url.Action("xemChiTiet","Sach",new {@maSach= item.MaSach })"><img title="@item.TenSach" src="@Url.Content("~/imgSP/" + item.AnhBia)" /></a>
                </div>
                <div id="thongTin">
                    @if (item.TenSach.Length < 30)
                    {
                        <div id="tenSach" title="@item.TenSach">
                            @item.TenSach
                        </div>
                        <br />
                        <div id="xemChiTiet" style="margin-top:-30px;" title="@item.TenSach"><a href="@Url.Action("xemChiTiet","Sach",new {@maSach=item.MaSach })">Xem chi tiết...</a></div>
                    }
                    else
                    {
                        <div id="tenSach" title="@item.TenSach">@item.TenSach.Substring(0, 30)...</div>
                        <br />
                        <div id="xemChiTiet" style="margin-top:-30px;" title="@item.TenSach"><a href="@Url.Action("xemChiTiet","Sach",new {@maSach=item.MaSach })">Xem chi tiết...</a></div>
                    }
                    @if (item.GiaBan < 1000000)
                    {
                        <div id="donGia" style="color:orange;font-size:20px;"><strong><font color="Green">Giá: </font></strong>@string.Format("{0:#.000}", Convert.ToDecimal(item.GiaBan) / 1000)đ</div>
                    }
                </div>
                @using (Html.BeginForm("ThemGioHang", "GioHang", new { @iMaSach = item.MaSach, @strUrl = Request.Url.ToString() }))
                {
                    <button type="submit" class="editBtn btn btn-danger" onclick="alert('Đã thêm vào giỏ hàng')"
                            style="background-color:rgb(255, 106, 0);width:250px;cursor:pointer">
                        <i class="fas fa-shopping-cart" style="color:black"> Mua hàng</i>
                    </button>
                    @*<input type="submit"  value="muahang" class="button danger"/>*@
                }
            </div>

            if (i % 3 == 0)
            {
                <div style="clear:both"></div>
            }
        }
    }

</div>
<div style="clear:both"></div>

@*tao link lien ket cac trang*@
<div id="PhanTrang">
    <div class="abc">
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

    </div>

    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("KetQuaTimKiem", "TimKiem", new { @page = page, sTuKhoa = ViewBag.TuKhoa }))
    </div>

</div>

<style>
    .MenuTrang li {
        padding: 0;
        margin: 0;
        border: none;
        display: inline;
        width: 40px;
        height: 40px;
        padding: 5px;
        margin: 5px;
        line-height: 45px;
        font-family: 'Times New Roman', Times, serif;
        font-weight: bold;
    }

    #PhanTrang {
        border-bottom: 1px solid #C9E4D6;
    }

    .abc {
        margin-left: 35px;
        margin-top: 5px;
        font-size: 25px;
        font-weight: bold;
        font-family: 'Times New Roman', Times, serif;
    }

    #divBody .editBtn button:hover {
    }
</style>

BookStore/Views/TimKiem/KetQuaTimKiemCD.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<BookStore.Models.ChuDe>
@{
    ViewBag.Title = "KetQuaTimKiemCD";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}


<hr style="padding:0;margin:0;border:none;background-color:black;" />
<div id="sachMoiXuatBan" style="clear:both;padding:13px 0px 0px 0px;font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;font-weight:bold;margin-left:90px;background-color:white;background:white">
    <h2>Kết quả tìm kiếm: </h2>
    @ViewBag.ThongBao
</div>
<br />
@using (Html.BeginForm("KetQuaTimKiemCD", "TimKiem", FormMethod.Post))
{
    @Html.TextBox("txtTimKiem", "", htmlAttributes:
new {@class="textboxTimKiem",@placeholder="Nhập tên chủ đề cần tìm....." })
    <button type="submit" style="padding: 0px 0px 0px 0px">
        <img src="~/img/search1.png" width="30px" height="30px" />
    </button>

}
<hr />
<table class="table" style="clear:both">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().MaChuDe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TenChuDe)
        </th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaChuDe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenChuDe)
            </td>
            <td>
                <a href="@Url.Action("ChinhSuaCD","QuanLySanPham", new { @MaCD = item.MaChuDe }) ">Chỉnh sửa</a>


            </td>
        </tr>
    }
</table>

<div id="PhanTrang">
    <div class="abc">
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

    </div>

    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("KetQuaTimKiemCD", "TimKiem", new { @page = page, sTuKhoa = ViewBag.TuKhoa }))
    </div>

</div>

<style>
    .MenuTrang li {
        padding: 0;
        margin: 0;
        border: none;
        display: inline;
        width: 40px;
        height: 40px;
        padding: 5px;
        margin: 5px;
        line-height: 45px;
        font-family: 'Times New Roman', Times, serif;
        font-weight: bold;
    }

    #PhanTrang {
        border-bottom: 1px solid #C9E4D6;
    }

    .abc {
        margin-left: 35px;
        margin-top: 5px;
        font-size: 25px;
        font-weight: bold;
        font-family: 'Times New Roman', Times, serif;
    }

    #divBody .editBtn button:hover {
    }
</style>

BookStore/Views/TimKiem/KetQuaTimKiemKH.cshtml
@model IEnumerable<BookStore.Models.KhachHang>

@{
    ViewBag.Title = "KetQuaTimKiemKH";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<hr />

<div style="margin-left:30%;">
    <h1>Thông tin khách hàng</h1>
</div>
<div id="sachMoiXuatBan" style="clear:both;padding:0px 0px 0px 0px;font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;font-weight:bold;margin-left:90px;background-color:white;background:white">
    <h2>Kết quả tìm kiếm: </h2>
    @ViewBag.ThongBao
</div>
<hr style="background-color:black" />
@using (Html.BeginForm("KetQuaTimKiemKH", "TimKiem", FormMethod.Post))
{
    @Html.TextBox("txtTimKiem", "", htmlAttributes:
new {@class="textboxTimKiem",@placeholder="Nhập tên khách hàng cần tìm....." })
    <button type="submit" style="padding: 0px 0px 0px 0px">
        <img src="~/img/search1.png" width="30px" height="30px" />
    </button>

}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MaKH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoTen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TaiKhoan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MatKhau)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DiaChi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DienThoai)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaKH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoTen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TaiKhoan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MatKhau)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgaySinh)
            </td>
            <td id="TaoMoi1">
                @Html.ActionLink("Chỉnh sửa", "SuaThongTin", new { @maKH = item.MaKH }) <br />
                @Html.ActionLink("Hiển Thị", "HienThiThongTin", new { @maKH = item.MaKH }) <br />

            </td>
        </tr>
    }

</table>
<style>
    #TaoMoi1 a {
        color: black;
        width: auto;
        height: auto;
        -webkit-transition: all .5s ease-out;
    }

        #TaoMoi1 a:hover {
            background-color: coral;
            -webkit-transition: all .5s ease-out;
            text-decoration: underline;
        }
</style>

BookStore/Views/TimKiem/KetQuaTimKiemNXB.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<BookStore.Models.NhaXuatBan>
@{
    ViewBag.Title = "KetQuaTimKiemNXB";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}


<hr style="padding:0;margin:0;border:none;background-color:black;" />
<div id="sachMoiXuatBan" style="clear:both;padding:13px 0px 0px 0px;font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;font-weight:bold;margin-left:90px;background-color:white;background:white">
    <h2>Kết quả tìm kiếm: </h2>
    @ViewBag.ThongBao
</div>
<br />
@using (Html.BeginForm("KetQuaTimKiemNXB", "TimKiem", FormMethod.Post))
{
    @Html.TextBox("txtTimKiem", "", htmlAttributes:
new {@class="textboxTimKiem",@placeholder="Nhập tên nhà xuất bản cần tìm....." })
    <button type="submit" style="padding: 0px 0px 0px 0px">
        <img src="~/img/search1.png" width="30px" height="30px" />
    </button>

}
<hr />
<table class="table" style="clear:both">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().MaNXB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TenNXB)
        </th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaNXB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenNXB)
            </td>
            <td>
                <a href="@Url.Action("ChinhSuaNXB","QuanLySanPham", new { @MaNXB = item.MaNXB }) ">Chỉnh sửa</a>


            </td>
        </tr>
    }
</table>

<div id="PhanTrang">
    <div class="abc">
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

    </div>

    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("KetQuaTimKiemNXB", "TimKiem", new { @page = page, sTuKhoa = ViewBag.TuKhoa }))
    </div>

</div>

<style>
    .MenuTrang li {
        padding: 0;
        margin: 0;
        border: none;
        display: inline;
        width: 40px;
        height: 40px;
        padding: 5px;
        margin: 5px;
        line-height: 45px;
        font-family: 'Times New Roman', Times, serif;
        font-weight: bold;
    }

    #PhanTrang {
        border-bottom: 1px solid #C9E4D6;
    }

    .abc {
        margin-left: 35px;
        margin-top: 5px;
        font-size: 25px;
        font-weight: bold;
        font-family: 'Times New Roman', Times, serif;
    }

    #divBody .editBtn button:hover {
    }
</style>