BookStore/Controllers/ChuDeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
namespace BookStore.Controllers
{
    public class ChuDeController : Controller
    {

        QLBanSachEntities5 db = new QLBanSachEntities5();
        
        
        // GET: ChuDe
        public ActionResult ChuDePartial()
        {

            return PartialView(db.ChuDes.Take(5).ToList());
        }
        
        //Tìm sách theo chủ đề
        public ViewResult timSachTheoChuDe(int maChuDe = 0)
        {
            //Kiểm tra chủ đề tồn tại   
            ChuDe chude = db.ChuDes.SingleOrDefault(n => n.MaChuDe == maChuDe);

            ViewBag.lstChuDe = db.ChuDes.ToList();
            
            if (chude == null)
            {
                Response.StatusCode = 404;
                return null;
            }
                //Truy xuất danh sách theo chủ đề
                List<SAch> lstSach = db.SAches.Where(n => n.MaChuDe == maChuDe).OrderBy(n => n.GiaBan).ToList();
                if (lstSach.Count == 0)
                {
                    ViewBag.Sach = "Không có sách nào thuộc chủ đề này.";
                }

            ViewBag.TenChuDe = db.ChuDes.Single(n => n.MaChuDe == maChuDe).TenChuDe;

            return View(lstSach);
        }
        public ViewResult hienThiTatCaChuDe()
        {
            return View(db.ChuDes.ToList());
        }

    }
}

BookStore/Controllers/NXBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
namespace BookStore.Controllers
{
    public class NXBController : Controller
    {
        QLBanSachEntities5 db = new QLBanSachEntities5();
        // GET: NXB
        public PartialViewResult NXBPartial()
        {
            return PartialView(db.NhaXuatBans.Take(8).OrderBy(n => n.TenNXB).ToList());
        }
        //Hienthisachtheonhaxuatban
        public ViewResult hienThiTacCaNXB(int maNXB =0)
        {
            NhaXuatBan NXB = db.NhaXuatBans.SingleOrDefault(n => n.MaNXB == maNXB);
            ViewBag.lstNXB = db.NhaXuatBans.ToList();
            if (NXB == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Truy xuất danh sách theo NXB
            List<SAch> lstSach = db.SAches.Where(n => n.MaNXB == maNXB).OrderBy(n => n.GiaBan).ToList();
            if (lstSach.Count == 0)
            {
                ViewBag.Sach = "Không có sách nào thuộc nhà xuất bản này.";
            }
            ViewBag.TenNXB = db.NhaXuatBans.Single(n => n.MaNXB == maNXB).TenNXB;
            return View(lstSach);
        }

        public ViewResult hienThiDanhMucNXB()
        {
            return View(db.NhaXuatBans.ToList());
        }
    }
}

BookStore/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
using PagedList;
using PagedList.Mvc;
namespace BookStore.Controllers
{
    public class SachController : Controller
    {
        QLBanSachEntities5 db = new QLBanSachEntities5();
        // GET: Sach


        public PartialViewResult SachMoiPartial()
        {
            var listSachMoi = db.SAches.Take(3).ToList();
            return PartialView(listSachMoi);
        }
        public ViewResult xemChiTiet(int maSach =0)
        {
            SAch sach = db.SAches.SingleOrDefault(n=>n.MaSach == maSach);
            if (sach == null)
            {
                //Tra ve trang bao loi
                Response.StatusCode = 404;
                return null;
            }
            if(Session["TaiKhoan"] != null)
            {
                KhachHang kh = (KhachHang) Session["TaiKhoan"];
                KhachHang kh1 = db.KhachHangs.Single(n => n.MaKH == kh.MaKH);
                if (kh1.LuotXem == null)
                    kh1.LuotXem = 1;
                else
                    kh1.LuotXem += 1;
                db.SaveChanges();
            }
            if(sach.LuotXem == null)
                sach.LuotXem = 1;
            else
                sach.LuotXem += 1;

            db.SaveChanges();

            ViewBag.TenChuDe = db.ChuDes.Single(n => n.MaChuDe == sach.MaChuDe).TenChuDe;
            ViewBag.NhaXuatBan = db.NhaXuatBans.Single(n => n.MaNXB == sach.MaNXB).TenNXB;
            return View(sach);
        }

        public ViewResult hienThiSachMoi(int? page)
        {   
            int pageSize = 6;
            //tao bien so trang
            int pageNumber = (page ?? 1);
            return View(db.SAches.Where(n => n.Moi == 1).ToList().OrderBy(n => n.GiaBan).ToPagedList(pageNumber, pageSize));
        }
    }
}

BookStore/Views/Layout/AdminLayout.cshtml
<!DOCTYPE html>

<html lang ="vi">
<head>

    <meta charset="UTF-8">
    <title>@ViewBag.Title</title>
    <link href="~/Content/templateAdmin/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/templateAdmin/css/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="~/Content/templateAdmin/css/style.css" rel="stylesheet" />
    <link href="~/Content/templateAdmin/css/style-responsive.css" rel="stylesheet" />
    <link href="~/Content/fontawesome-free-5.8.1-web/css/all.min.css" rel="stylesheet" />
    <link href="~/Content/admincss/animate.min.css" rel="stylesheet" />
    <link href="~/Content/admincss/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/admincss/demo.css" rel="stylesheet" />
    <link href="~/Content/admincss/light-bootstrap-dashboard.css" rel="stylesheet" />
    <script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
</head>
<body>

    <div class="wrapper">
        <div class="sidebar" data-color="red" data-image="assets/img/sidebar-5.jpg" >

            <!--

                Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
                Tip 2: you can also add an image using data-image tag

            -->

            <div class="sidebar-wrapper">


                <ul class="nav">
                    <li>
                        <a href="@Url.Action("Index","QuanLySanPham")"><i style="line-height:70%" class="fas fa-book-reader"></i><strong><span class="hidden-tablet"> Quản lý sản phẩm</span></strong></a>
                    </li>

                    <li>
                        <a href="@Url.Action("ThemMoi","QuanLySanPham")"><i style="line-height:70%" class="fas fa-plus"></i><strong><span class="hidden-tablet"> Thêm mới sách</span></strong></a>
                    </li>
                    <li>
                        <a href="@Url.Action("ThemChuDe","QuanLySanPham")"><i style="line-height:70%" class="fas fa-plus"></i><strong><span class="hidden-tablet"> Thêm chủ đề</span></strong></a>
                    </li>
                    <li>
                        <a href="@Url.Action("ThemNXB","QuanLySanPham")"><i style="line-height:70%" class="fas fa-plus"></i><strong><span class="hidden-tablet"> Thêm nhà xuất bản</span></strong></a>
                    </li>
                    <li>
                        <a href="@Url.Action("XemChuDe","QuanLySanPham")"><i style="line-height:70%" class="fas fa-eye"></i><strong><span class="hidden-tablet"> Xem chủ đề</span></strong></a>
                    </li>
                    <li>
                        <a href="@Url.Action("XemNXB","QuanLySanPham")"><i style="line-height:70%" class="fas fa-eye"></i><strong><span class="hidden-tablet"> Xem nhà xuất bản</span></strong></a>
                    </li>
                    <li>
                        <a href="@Url.Action("XemDonHang","QuanLySanPham")"><i style="line-height:70%" class="fas fa-eye"></i><strong><span class="hidden-tablet"> Xem đơn hàng</span></strong></a>
                    </li>
                    <li>
                        <a href="@Url.Action("XemThongTinKhachHang","QuanLySanPham")"><i style="line-height:70%" class="fas fa-eye"></i><strong><span class="hidden-tablet">Thông tin khách hàng</span></strong></a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index","ThongKe")"><i style="line-height:70%" class="fas fa-chart-pie"></i><strong><span class="hidden-tablet">Thống kê lượt xem sách</span></strong></a>
                    </li>

                    <li>
                        <a href="@Url.Action("ThongKe2","ThongKe")"><i style="line-height:70%" class="fas fa-chart-pie"></i><strong><span class="hidden-tablet">Thống kê lượt khách xem sách</span></strong></a>
                    </li>
                    <li>
                        <a href="#"><i style="line-height:70%" class="fas fa-chart-pie"></i><strong><span class="hidden-tablet">Thống kê lượt khách đăng nhập</span></strong></a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="main-panel">
            <nav class="navbar navbar-default navbar-fixed">
                <div class="container-fluid">

                    <div class="collapse navbar-collapse">


                        <ul class="nav navbar-nav navbar-right ">
                            
                            <li>
                                <a href="@Url.Action("Index","Home")">
                                    <p>Trở về trang chủ</p>
                                </a>
                            </li>

                            <li class="separator hidden-lg"></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div style="padding-left:5px; background-color:white"   >
                @RenderBody()
            </div>
        </div>
    </div>


</body>
<!--   Core JS Files   -->
<script src="assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>

<!--  Charts Plugin -->
<script src="assets/js/chartist.min.js"></script>

<!--  Notifications Plugin    -->
<script src="assets/js/bootstrap-notify.js"></script>

<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

<!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
<script src="assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
<script src="assets/js/demo.js"></script>

<script type="text/javascript">
    $(document).ready(function () {

        demo.initChartist();

        $.notify({
            icon: 'pe-7s-gift',
            message: "Welcome to <b>Light Bootstrap Dashboard</b> - a beautiful freebie for every web developer."

        }, {
                type: 'info',
                timer: 4000
            });

    });
</script>
</html>

BookStore/Views/Layout/NguoiDungLayout.cshtml
    
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/NguoiDungCss/fonts.css" rel="stylesheet" />
    <link href="~/Content/NguoiDungCss/screen.css" rel="stylesheet" />
    <link href="~/Content/NguoiDungCss/StyleSheet1.css" rel="stylesheet" />
    <link href="~/Content/fontawesome-free-5.8.1-web/css/all.min.css" rel="stylesheet" />
    <link href="~/nivo slider/nivo-slider.css" rel="stylesheet" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="jquery.nivo.slider.js"></script>
    <script src="~/nivo slider/jquery.nivo.slider.pack.js"></script>
    <link href="~/Content/search.css" rel="stylesheet" />
  
    @*@import url('https://fonts.googleapis.com/css?family=Inconsolata:700');*@
</head>

<body>
  
    <div id="ToanTrang">

        <section class="blank">
            <div class="flash">
                <div class="icDienthoai">
                    <a href="#"><i class="fas fa-phone "></i>  (083)0909783</a>
                </div>
                <div class="Dangkydangnhap">
                    @Html.Action("GioHangPartial", "GioHang")|
                    <span id="hienthiDanKy">
                        <a href="@Url.Action("DangKy","NguoiDung")"><i class="fas fa-user "></i>Đăng ký </a>|
                    </span>
                     
                  
                    @*<a href="@Url.Action("DangNhap","NguoiDung")"><i class="fas fa-sign-in-alt "></i>Đăng nhập</a>*@
                    @Html.Action("DangNhap1", "NguoiDung")|
                    @if (Session["admin"] != null)
                    {
                      
                    <a href="@Url.Action("Index","QuanLySanPham")">Trang Quản Lý |</a>
                    
                    }
                    @if (Session["TaiKhoan"] != null)
                    {
                    @Html.ActionLink("Thoát", "Thoat", "NguoiDung")
                    }
                </div>
            </div>  


            <div class="flash success" id="divdanhmuc">
                <div id="hopthoaitimkiem">
                    @using (Html.BeginForm("KetQuaTimKiem", "TimKiem", FormMethod.Post))
                    {
                        @Html.TextBox("txtTimKiem", "", htmlAttributes:
            new {@class="textboxTimKiem",@placeholder="Nhập vào từ khóa cần tìm..." })

                            
                        <button type="submit" style="padding: 0px 0px 0px 0px;position:absolute;top:25px; left:250px">
                            <img src="~/img/search1.png" style="width:30px;height:30px;" />
                        </button>
                    }
                </div>

                @*menu ben phai*@
                <ul class="navdanhmuc">
                    <li >
                        <div style="display:inline-block">
                            <a href="@Url.Action("Index","Home")">Trang chủ</a>
                        </div>
                    </li>
                    <li>
                        <a href="#">Liên hệ</a>
                    </li>
                    <li>
                        <a href="@Url.Action("HuongDan","TongHop")">Hướng Dẫn</a>
                    </li>
                    <li>
                        <a href="#">Giới thiệu</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Home")">Sách</a>
                    </li>
                </ul>
            </div>

        </section>

        <section id="anleftslider">

            <div id="leftslider">

                @*ChenPartial*@
                <div class="activity">

                    @Html.Action("SachMoiPartial", "Sach")

                </div>
            </div>
            <div id="slider" class="nivoSlider">
                <img src="~/img/slider1.jpg" />
                @*<img src="~/img/slider2.jpg" />
                <img src="~/img/slider3.jpg" />
                <img src="~/img/slider4.jpg" />*@
                
            </div>
            @*<h2 style="clear:both;font-weight:bold">Chào mừng các bạn đến với BookStore của chúng tôi. (^_^)</h2>*@
            <div style="clear:both">

            </div>
        </section>



        @*div body, index*@
        <div id="noiDung" style="background-color:white">
            @RenderBody()
        </div>

        <section id="chudeHienThi">
            @*ChuDe*@
            <div>
                @Html.Action("ChuDePartial","ChuDe")
                
            </div>
        </section>

        @*div nha xuat ban*@
        <section id="nxbHienThi" class="blank items" style="background-color:white">
            <div id="nxbleft">
                <div class="item">
                    <div class="item-info">
                        @Html.Action("NXBPartial","NXB")
                        
                    </div>
                    <img src="https://yt3.ggpht.com/a-/AAuE7mDGN4WmsOPvQURqbOiac_2JV6ntwAFVXQIzVg=s900-mo-c-c0xffffffff-rj-k-no" alt="Image" style="height:380px" />
                </div>
            </div>
            <div id="nxbright" style="background-color:white">
                @RenderSection("Noidungbenphai",false)
            </div>
            <div style="clear:both; background-color:white" >
                <a href="#" class="button button-buy">
                    CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ MÊ KÔNG COM

                    Địa chỉ: 52/2 Thoại Ngọc Hầu, Phường Hòa Thạnh, Quận Tân Phú, Hồ Chí Minh
                    MST: 0303615027 do Sở Kế Hoạch Và Đầu Tư Tp.HCM cấp ngày 10/03/2011
                    Tel: 028.73008182 - Fax: 028.39733234 - Email: hotro@vinabook.comasdas
                </a>
            </div>
        </section>

    </div>

    <script type="text/javascript">
        $(window).load(function () {
            $('#slider').nivoSlider({
                controlNav: false,
                nextText: '',
                prevText: ''
            });
        });
    </script>
</body>
</html>